const swaggerJsdoc = require('swagger-jsdoc')

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Kế Toán Tâm An — API',
      version: '1.0.0',
      description: 'Internal management API for Ke Toan Tam An accounting firm.',
    },
    servers: [{ url: '/api', description: 'Development server' }],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Access token (15 min). Obtain via POST /api/auth/login',
        },
      },
      schemas: {
        Error: {
          type: 'object',
          properties: {
            error: { type: 'string' },
            message: { type: 'string' },
          },
        },
        Pagination: {
          type: 'object',
          properties: {
            page:       { type: 'integer', example: 1 },
            limit:      { type: 'integer', example: 20 },
            total:      { type: 'integer', example: 100 },
            totalPages: { type: 'integer', example: 5 },
          },
        },
        UserSafe: {
          type: 'object',
          properties: {
            id:          { type: 'string', format: 'uuid' },
            name:        { type: 'string', example: 'Nguyễn Văn A' },
            email:       { type: 'string', format: 'email' },
            role:        { type: 'string', enum: ['admin', 'staff'] },
            status:      { type: 'string', enum: ['active', 'on_leave', 'resigned'] },
            phone:       { type: 'string', nullable: true },
            jobTitle:    { type: 'string', nullable: true },
            avatarUrl:   { type: 'string', nullable: true },
            mustChangePw: { type: 'boolean' },
            lastLoginAt:  { type: 'string', format: 'date-time', nullable: true },
            createdAt:    { type: 'string', format: 'date-time' },
            updatedAt:    { type: 'string', format: 'date-time', nullable: true },
          },
        },
        Company: {
          type: 'object',
          properties: {
            id:               { type: 'string', format: 'uuid' },
            name:             { type: 'string', example: 'Công ty TNHH ABC' },
            taxCode:          { type: 'string', nullable: true, example: '0123456789' },
            address:          { type: 'string', nullable: true },
            businessType:     { type: 'string', enum: ['TNHH', 'CP', 'HKD', 'DN_TU_NHAN', 'KHAC'] },
            industry:         { type: 'string', nullable: true },
            status:           { type: 'string', enum: ['active', 'inactive', 'terminated'] },
            legalRepName:     { type: 'string', nullable: true },
            legalRepPhone:    { type: 'string', nullable: true },
            contactName:      { type: 'string', nullable: true },
            contactPhone:     { type: 'string', nullable: true },
            contactEmail:     { type: 'string', format: 'email', nullable: true },
            bankAccount:      { type: 'string', nullable: true },
            bankName:         { type: 'string', nullable: true },
            serviceStartDate: { type: 'string', format: 'date', nullable: true },
            notes:            { type: 'string', nullable: true },
            assignedStaffId:  { type: 'string', format: 'uuid', nullable: true },
            assignedStaffName: { type: 'string', nullable: true },
            taskOpenCount:    { type: 'integer', example: 3 },
            taskOverdueCount: { type: 'integer', example: 1 },
            createdAt:        { type: 'string', format: 'date-time' },
            updatedAt:        { type: 'string', format: 'date-time', nullable: true },
          },
        },
        Assignment: {
          type: 'object',
          properties: {
            id:          { type: 'string', format: 'uuid' },
            companyId:   { type: 'string', format: 'uuid' },
            staffId:     { type: 'string', format: 'uuid' },
            staffName:   { type: 'string', example: 'Nguyễn Văn B' },
            startDate:   { type: 'string', format: 'date' },
            endDate:     { type: 'string', format: 'date', nullable: true },
            notes:       { type: 'string', nullable: true },
            assignedBy:  { type: 'string', format: 'uuid', nullable: true },
            createdAt:   { type: 'string', format: 'date-time' },
          },
        },
        TaskType: {
          type: 'object',
          properties: {
            id:             { type: 'string', format: 'uuid' },
            name:           { type: 'string', example: 'Khai thuế GTGT hàng tháng' },
            groupName:      { type: 'string', nullable: true, example: 'Khai thuế' },
            description:    { type: 'string', nullable: true },
            defaultSlaDays: { type: 'integer', example: 7 },
            isActive:       { type: 'boolean' },
            createdBy:      { type: 'string', format: 'uuid', nullable: true },
            createdAt:      { type: 'string', format: 'date-time' },
            updatedAt:      { type: 'string', format: 'date-time', nullable: true },
          },
        },
        TaskTypeDetail: {
          allOf: [
            { '$ref': '#/components/schemas/TaskType' },
            {
              type: 'object',
              properties: {
                checklist:    { type: 'array', items: { '$ref': '#/components/schemas/ChecklistStep' } },
                customFields: { type: 'array', items: { '$ref': '#/components/schemas/CustomFieldSchema' } },
              },
            },
          ],
        },
        ChecklistStep: {
          type: 'object',
          properties: {
            id:        { type: 'string', format: 'uuid' },
            stepOrder: { type: 'integer', example: 1 },
            stepText:  { type: 'string', example: 'Thu thập chứng từ đầu vào' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        Schedule: {
          type: 'object',
          properties: {
            id:                 { type: 'string', format: 'uuid' },
            companyId:          { type: 'string', format: 'uuid' },
            taskTypeId:         { type: 'string', format: 'uuid' },
            taskTypeName:       { type: 'string', nullable: true },
            assignedStaffId:    { type: 'string', format: 'uuid', nullable: true },
            assignedStaffName:  { type: 'string', nullable: true },
            recurrenceType:     { type: 'string', enum: ['daily', 'weekly', 'monthly_by_date', 'monthly_by_weekday', 'monthly_last_day', 'quarterly', 'yearly', 'custom_dates', 'once'] },
            recurrenceConfig:   { type: 'object', description: 'Config varies per recurrenceType' },
            deadlineOffsetDays: { type: 'integer', example: 0 },
            overrideSlaDays:    { type: 'integer', nullable: true },
            notes:              { type: 'string', nullable: true },
            isActive:           { type: 'boolean' },
            lastGeneratedAt:    { type: 'string', format: 'date-time', nullable: true },
            createdAt:          { type: 'string', format: 'date-time' },
            updatedAt:          { type: 'string', format: 'date-time' },
          },
        },
        Task: {
          type: 'object',
          properties: {
            id:                     { type: 'string', format: 'uuid' },
            title:                  { type: 'string', example: 'Kê khai GTGT — T05/2026' },
            description:            { type: 'string', nullable: true },
            companyId:              { type: 'string', format: 'uuid' },
            companyName:            { type: 'string', nullable: true },
            taskTypeId:             { type: 'string', format: 'uuid', nullable: true },
            taskTypeName:           { type: 'string', nullable: true },
            customerTaskScheduleId: { type: 'string', format: 'uuid', nullable: true },
            assignedTo:             { type: 'string', format: 'uuid', nullable: true },
            assignedToName:         { type: 'string', nullable: true },
            assignedBy:             { type: 'string', format: 'uuid', nullable: true },
            status:                 { type: 'string', enum: ['pending', 'in_progress', 'on_hold', 'pending_review', 'needs_revision', 'completed'] },
            priority:               { type: 'string', enum: ['low', 'medium', 'high', 'urgent'] },
            source:                 { type: 'string', enum: ['auto', 'manual'] },
            dueDate:                { type: 'string', format: 'date', nullable: true },
            periodLabel:            { type: 'string', nullable: true, example: 'T05/2026' },
            completedAt:            { type: 'string', format: 'date-time', nullable: true },
            onHoldReason:           { type: 'string', nullable: true },
            slaDays:                { type: 'integer', nullable: true },
            actualHours:            { type: 'number', nullable: true },
            checklistTotal:         { type: 'integer', example: 5 },
            checklistDone:          { type: 'integer', example: 3 },
            createdBy:              { type: 'string', format: 'uuid' },
            createdAt:              { type: 'string', format: 'date-time' },
            updatedAt:              { type: 'string', format: 'date-time' },
          },
        },
        ActivityLog: {
          type: 'object',
          properties: {
            id:        { type: 'string', format: 'uuid' },
            userId:    { type: 'string', format: 'uuid', nullable: true },
            userName:  { type: 'string', nullable: true },
            action:    { type: 'string', example: 'status_changed' },
            oldValue:  { type: 'string', nullable: true },
            newValue:  { type: 'string', nullable: true },
            meta:      { type: 'object', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        CustomFieldSchema: {
          type: 'object',
          properties: {
            id:           { type: 'string', format: 'uuid' },
            fieldKey:     { type: 'string', example: 'so_to_khai' },
            label:        { type: 'string', example: 'Số tờ khai' },
            dataType:     { type: 'string', enum: ['text', 'number', 'date', 'boolean', 'select'] },
            options:      { type: 'array', items: { type: 'string' }, nullable: true },
            isRequired:   { type: 'boolean' },
            displayOrder: { type: 'integer' },
            createdAt:    { type: 'string', format: 'date-time' },
          },
        },

        // --- Phase 7: Task Extensions ---
        TaskChecklistItem: {
          type: 'object',
          properties: {
            id:          { type: 'string', format: 'uuid' },
            taskId:      { type: 'string', format: 'uuid' },
            stepOrder:   { type: 'integer', example: 1 },
            stepText:    { type: 'string', example: 'Thu thập chứng từ đầu vào' },
            isCompleted: { type: 'boolean' },
            completedBy: { type: 'string', format: 'uuid', nullable: true },
            completedAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt:   { type: 'string', format: 'date-time' },
          },
        },
        TaskDependency: {
          type: 'object',
          properties: {
            id:              { type: 'string', format: 'uuid' },
            taskId:          { type: 'string', format: 'uuid' },
            dependsOnTaskId: { type: 'string', format: 'uuid' },
            dependsOnTitle:  { type: 'string', nullable: true },
            dependsOnStatus: { type: 'string', nullable: true },
            createdBy:       { type: 'string', format: 'uuid' },
            createdAt:       { type: 'string', format: 'date-time' },
          },
        },
        TaskComment: {
          type: 'object',
          properties: {
            id:        { type: 'string', format: 'uuid' },
            taskId:    { type: 'string', format: 'uuid' },
            userId:    { type: 'string', format: 'uuid' },
            userName:  { type: 'string', nullable: true },
            content:   { type: 'string' },
            isEdited:  { type: 'boolean' },
            editedAt:  { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        TaskTimeLog: {
          type: 'object',
          properties: {
            id:         { type: 'string', format: 'uuid' },
            taskId:     { type: 'string', format: 'uuid' },
            userId:     { type: 'string', format: 'uuid' },
            userName:   { type: 'string', nullable: true },
            hours:      { type: 'number', example: 2.5 },
            note:       { type: 'string', nullable: true },
            loggedDate: { type: 'string', format: 'date' },
            createdAt:  { type: 'string', format: 'date-time' },
          },
        },
        TaskCustomFieldValue: {
          type: 'object',
          properties: {
            fieldSchemaId: { type: 'string', format: 'uuid' },
            fieldKey:      { type: 'string', example: 'ky_khai' },
            label:         { type: 'string', example: 'Kỳ khai' },
            dataType:      { type: 'string', enum: ['text', 'number', 'date', 'boolean', 'select'] },
            options:       { type: 'array', items: { type: 'string' }, nullable: true },
            isRequired:    { type: 'boolean' },
            displayOrder:  { type: 'integer' },
            value:         { nullable: true, oneOf: [{ type: 'string' }, { type: 'number' }, { type: 'boolean' }] },
            updatedAt:     { type: 'string', format: 'date-time', nullable: true },
          },
        },

        // --- Phase 8: Scheduler ---
        SchedulerStatus: {
          type: 'object',
          properties: {
            active:        { type: 'boolean', description: 'Cron job đang chạy' },
            isRunning:     { type: 'boolean', description: 'Đang trong vòng chạy hiện tại' },
            lastRunAt:     { type: 'string', format: 'date-time', nullable: true },
            lastRunResult: {
              type: 'object',
              nullable: true,
              properties: {
                generated:  { type: 'integer' },
                skipped:    { type: 'integer' },
                errors:     { type: 'integer' },
                durationMs: { type: 'integer' },
              },
            },
          },
        },

        // --- Phase 9: Credentials ---
        Credential: {
          type: 'object',
          properties: {
            id:         { type: 'string', format: 'uuid' },
            companyId:  { type: 'string', format: 'uuid' },
            systemName: { type: 'string', example: 'Cổng thuế điện tử eTax' },
            systemUrl:  { type: 'string', format: 'uri', nullable: true, example: 'https://etax.gdt.gov.vn' },
            username:   { type: 'string', example: 'MST0123456789' },
            password:   { type: 'string', example: '***', description: 'Luôn là "***" trừ khi gọi /reveal' },
            notes:      { type: 'string', nullable: true },
            isActive:   { type: 'boolean' },
            createdBy:  { type: 'string', format: 'uuid' },
            updatedBy:  { type: 'string', format: 'uuid', nullable: true },
            createdAt:  { type: 'string', format: 'date-time' },
            updatedAt:  { type: 'string', format: 'date-time' },
          },
        },

        // --- Phase 10: Payroll ---
        PayrollPeriod: {
          type: 'object',
          properties: {
            id:          { type: 'string', format: 'uuid' },
            periodYear:  { type: 'integer', example: 2026 },
            periodMonth: { type: 'integer', example: 5 },
            startDate:   { type: 'string', format: 'date' },
            endDate:     { type: 'string', format: 'date' },
            status:      { type: 'string', enum: ['draft', 'confirmed', 'paid'] },
            notes:       { type: 'string', nullable: true },
            createdBy:   { type: 'string', format: 'uuid' },
            confirmedBy: { type: 'string', format: 'uuid', nullable: true },
            confirmedAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt:   { type: 'string', format: 'date-time' },
            updatedAt:   { type: 'string', format: 'date-time' },
          },
        },
        PayrollRecord: {
          type: 'object',
          properties: {
            id:              { type: 'string', format: 'uuid' },
            periodId:        { type: 'string', format: 'uuid' },
            userId:          { type: 'string', format: 'uuid' },
            userName:        { type: 'string', nullable: true },
            baseSalary:      { type: 'integer', example: 10000000 },
            allowances:      { type: 'integer', example: 1430000 },
            bonus:           { type: 'integer', example: 0 },
            grossIncome:     { type: 'integer', example: 11430000, description: 'Tự tính: base + allowances + bonus' },
            bhxhEmployee:    { type: 'integer', example: 800000 },
            bhytEmployee:    { type: 'integer', example: 150000 },
            bhtnEmployee:    { type: 'integer', example: 100000 },
            bhxhEmployer:    { type: 'integer', example: 1750000 },
            bhytEmployer:    { type: 'integer', example: 300000 },
            bhtnEmployer:    { type: 'integer', example: 100000 },
            pitDeduction:    { type: 'integer', example: 0 },
            otherDeductions: { type: 'integer', example: 0 },
            netSalary:       { type: 'integer', example: 10380000, description: 'Tự tính: gross - deductions NV' },
            components:      { type: 'object', nullable: true },
            notes:           { type: 'string', nullable: true },
            createdAt:       { type: 'string', format: 'date-time' },
            updatedAt:       { type: 'string', format: 'date-time' },
          },
        },

        // --- Phase 11: Documents ---
        Document: {
          type: 'object',
          properties: {
            id:             { type: 'string', format: 'uuid' },
            companyId:      { type: 'string', format: 'uuid' },
            taskId:         { type: 'string', format: 'uuid', nullable: true },
            fileName:       { type: 'string', example: 'BaoCaoThue_T05_2026.pdf' },
            category:       { type: 'string', enum: ['ho_so', 'bao_cao', 'hop_dong', 'chung_tu', 'thue', 'bao_hiem', 'khac'] },
            onedriveItemId: { type: 'string', example: '01ABCDEF...' },
            webUrl:         { type: 'string', format: 'uri', example: 'https://xxx.sharepoint.com/...' },
            sizeBytes:      { type: 'integer', nullable: true, example: 204800 },
            mimeType:       { type: 'string', nullable: true, example: 'application/pdf' },
            uploadedBy:     { type: 'string', format: 'uuid' },
            uploaderName:   { type: 'string', nullable: true },
            createdAt:      { type: 'string', format: 'date-time' },
            updatedAt:      { type: 'string', format: 'date-time' },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }],
    tags: [
      { name: 'Health',      description: 'System health check' },
      { name: 'Auth',        description: 'Authentication & session management' },
      { name: 'Users',       description: 'User & staff management' },
      { name: 'Companies',   description: 'Customer company profiles' },
      { name: 'Task Types',  description: 'Task type library (Layer 1)' },
      { name: 'Schedules',   description: 'Customer task schedules (Layer 2)' },
      { name: 'Tasks',       description: 'Task lifecycle management' },
      { name: 'Credentials', description: 'Encrypted credential vault' },
      { name: 'Payroll',     description: 'Payroll period management' },
      { name: 'Documents',   description: 'OneDrive document management' },
      { name: 'Notifications', description: 'In-app notifications' },
      { name: 'Reports',     description: 'Dashboard & reports' },
      { name: 'Admin',       description: 'Admin-only system operations' },
    ],
  },
  apis: ['./src/modules/**/*.router.js', './src/app.js'],
}

const swaggerSpec = swaggerJsdoc(options)

module.exports = swaggerSpec
